/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void testRoll(){
        int testResult = Main.roll(4).length;
        assertEquals(4,testResult);
    }
    @Test void testContainsDuplicates(){
        int[] testArray ={1,2,3,4,5};
        boolean testResult = Main.containsDuplicates(testArray);
        assertFalse(testResult);
    }
    @Test void testCalculatingAverages(){
        int[] testArray = {1,2,3};
        int testResult = Main.calculatingAverages(testArray);
        assertEquals(2,testResult);
    }
    @Test void testAverageOfArrays(){
        int[][] arrayToTest = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 57, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}};
        int[] arrayExpected = {55, 54, 60, 57, 59, 57, 61};
        int[] testResult = Main.averageOfArrays(arrayToTest);
        assertArrayEquals(arrayExpected, testResult);
    }
}