/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Main {
    public static void main(String[] args) {


        int[] userArrDup = new int[]{1, 2, 3, 4, 5, 6};
        int[] userAveragesArr = new int[]{1, 2, 3, 4, 5};

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 57, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}};

        System.out.println(Arrays.toString(roll(4)));
        System.out.println(containsDuplicates(userArrDup));
        System.out.println(calculatingAverages(userAveragesArr));
        System.out.println(Arrays.toString(averageOfArrays(weeklyMonthTemperatures)));

    }
    public static int[] roll(int times){
        int[] rollArray = new int[times];
        for (int i = 0; i < rollArray.length; i++){
            rollArray[i] = (int) Math.floor(Math.random()*(6-1+1)+1);
        }
        return rollArray;
    }

    public static boolean containsDuplicates(int[] userArray){
        for (int i = 0; i < userArray.length; i++){
            for (int j = i + 1; j < userArray.length; j++){

                if (userArray[i] == userArray[j]){
                    return true;
                }
            }
        }
        return false;
    }

    public static int calculatingAverages (int[] averagesArr){
        int total = 0;
        for (int i = 0; i < averagesArr.length; i++){
            total += averagesArr[i];
        }
        int average = total / averagesArr.length;
        return average;
    }

    public static int[] averageOfArrays (int[][] weeklyMonthTemperatures){

        int[] averageOfArrays = new int[weeklyMonthTemperatures.length];
        for (int i = 0; i < weeklyMonthTemperatures.length; i++){
            int sum = 0;
            for (int j = 0; j < weeklyMonthTemperatures[i].length; j++){
                sum = sum + weeklyMonthTemperatures[i][j];
            }
            int average = sum / weeklyMonthTemperatures[i].length;
            averageOfArrays[i] = average;
            // compare element inside average of array and get the lowest average
            if(averageOfArrays[i] < averageOfArrays[0]){
                // assign the array has the lowest average to averageOfArrays
                averageOfArrays = weeklyMonthTemperatures[i];
            }
        } return averageOfArrays;

    }

}
