/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Main {
    public static void main(String[] args) {
//        Restaurant restaurant = new Restaurant();
//        Review review = new Review();
    }
}
