/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class MainTest {
    @Test void testRestaurantClassConstructor(){
        Restaurant restaurant = new Restaurant("Abu saleh", 5,1);
        assertEquals("Abu saleh" ,restaurant.getRestaurantName());
        assertEquals(5 ,restaurant.getRestaurantStars());
        assertEquals(1 ,restaurant.getRestaurantNumberOfDollarSigns());
    }

    @Test void testToStringOfRestaurantClass(){
        Restaurant restaurant = new Restaurant("Hamada",4,2);
        assertEquals("Restaurant{restaurantName='Hamada'}", restaurant.toString());
    }

    @Test void testReviewClassConstructor(){
        Review review = new Review("wide","Ahmed",4);
        assertEquals("wide",review.getBodyOfReview());
        assertEquals("Ahmed",review.getAuthorOfReview());
        assertEquals(4,review.getNumberOfStarsForReview());
    }

    @Test void testToStringOfViewClass(){
        Review review = new Review("narrow","Ali", 5);
        assertEquals("Review{bodyOfReview='narrow', authorOfReview='Ali'}",review.toString());
    }
}
